name: assignmet
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://telemetry_user:password@postgres:5432/telemetry_db
    networks:
      - app-network
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./frontend:/app/frontend
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=telemetry_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=telemetry_db
    networks:
      - app-network
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
